#!/data/data/com.termux/files/usr/bin/bash

echo " "
echo " "
echo " "
echo "Ready to download"
echo " "
echo "For more information please visit"
echo "youtube-dl.org & reddit.com/r/youtubedl"
echo " "
echo "Video files are saved in Downloads/Media/Video"
echo " "
echo " "
command='-no-mtime -o /data/data/com.termux/files/home/storage/downloads/Media/Video/%(title)s.%(ext)s -f'
    echo "$command \"bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best\"" > ~/.config/youtube-dl/config
    youtube-dl $1

read -p "[Press enter]"

#Original Code Contributed By https://www.reddit.com/user/MagnificentBastard69
