#!/data/data/com.termux/files/usr/bin/bash

echo " "
echo " "
echo " "
echo "Ready to download"
echo " "
echo "For more information please visit"
echo "youtube-dl.org & reddit.com/r/youtubedl"
echo " "
echo "Audio files are saved in Downloads/Media/Audio"
echo "Video files are saved in Downloads/Media/Video"
echo " "
echo " "
echo "For MP3 Audio press 1"
echo "For M4A Audio press 2"
echo "For MP4 Video press 3"
echo "For MP3 & MP4 press 4"
echo "For M4A & MP4 press 5"
echo " "
command='-no-mtime -o /data/data/com.termux/files/home/storage/downloads/Media/Video/%(title)s.%(ext)s -f'

echo "--no-mtime -o /data/data/com.termux/files/home/storage/downloads/Media/Audio/%(title)s.%(ext)s -f140 -x" > ~/.config/youtube-dl/config
youtube-dl $1
echo "$command \"bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best\"" > ~/.config/youtube-dl/config
youtube-dl $1


Original Code Contributed By https://www.reddit.com/user/MagnificentBastard69
