#!/data/data/com.termux/files/usr/bin/bash


echo " "
#echo "Ready to download"
#echo "Audio files are saved in Downloads/Media/Video"
echo "Video files are saved in Downloads/Media/Audio"
echo " "
#echo "For MP4 Video press 1"
#echo "For M4A Audio press 2"
#echo "For MP3 Audio press 3"
#echo "For MP3 & MP4 press 4"
#echo "For M4A & MP4 press 5"
#echo " "
command='-no-mtime -o /data/data/com.termux/files/home/storage/downloads/Media/Video/%(title)s.%(ext)s -f'
#read option

#if [ "$option" -eq "1" ]
#then
#    clear
    echo "$command \"bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best\"" > ~/.config/youtube-dl/config
 
#elif [ "$option" -eq "2" ]
#then
#    clear
#    echo "--no-mtime -o /data/data/com.termux/files/home/storage/downloads/Media/Audio/%(title)s.%(ext)s -f140 -x" > ~/.config/youtube-dl/config

#elif [ "$option" -eq "3" ]
#then
#    clear
#    echo "--no-mtime -o /data/data/com.termux/files/home/storage/downloads/Media/Audio/%(title)s.%(ext)s -x --audio-format mp3 --audio-quality 192K --prefer-ffmpeg" > ~/.config/youtube-dl/config

#elif [ "$option" -eq "4" ]
#then
#    clear
#    echo "--no-mtime -o /data/data/com.termux/files/home/storage/downloads/Media/Audio/%(title)s.%(ext)s -x --audio-format mp3 --audio-quality 192K --prefer-ffmpeg" > ~/.config/youtube-dl/config
#    youtube-dl $1
#	echo "$command \"bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best\"" > ~/.config/youtube-dl/config

#elif [ "$option" -eq "5" ]
#then
#    clear
#    echo "--no-mtime -o /data/data/com.termux/files/home/storage/downloads/Media/Audio/%(title)s.%(ext)s -f140 -x" > ~/.config/youtube-dl/config
#    youtube-dl $1
#	echo "$command \"bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best\"" > ~/.config/youtube-dl/config

#fi
    youtube-dl $1 | grep --line-buffered -oP '^\[download\].*?\K([0-9.]+|#\d+ of \d)' > progress&

r="^[-+]?[0-9]+\.?[0-9]*$"
COUNTER=0
while [ $COUNTER -lt 101 ]
do
     progress=$(tail -n 1 progress)
     COUNTER=$(printf %.0f $progress)
	if [[ $COUNTER == 100 ]]; then
	   rm progress
	   am broadcast --user 0 -a Termux.NOTIFY -e title "Finished" -e text "Dowload complete" > /dev/null
	   exit 0
	fi
	if ! [[ $COUNTER =~ $r ]] || [[ $COUNTER -gt 100 ]]; then
	   COUNTER=0
	 else
	   COUNTER=$COUNTER
	   am broadcast --user 0 -a Termux.NOTIFY -e title "Downloading..." -e text "Termux test download" -e percent "$COUNTER" > /dev/null
	fi
     echo $COUNTER
     sleep 1
done && exit
